--ALTER TABLE [Hotel].[TbHotelRoomCapacity]
--ADD [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT GETUTCDATE() 
--   ,[ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),   
--PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo]); 

--ALTER TABLE [Hotel].[TbHotelRoomCapacity]   
--SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = Hotel.TbHotelRoomCapacityChanges));


---- SET SYSTEM_VERSIONING TO OFF
ALTER TABLE Hotel.TbHotelProvider
SET (SYSTEM_VERSIONING = OFF)
ALTER TABLE Hotel.TbHotelProvider Add RowVersion TimeStamp
--GO

--ALTER TABLE Hotel.TbHotelRoomCapacity
--DROP PERIOD FOR SYSTEM_TIME;

---- SET SYSTEM_VERSIONING TO ON
--ALTER TABLE Hotel.TbHotelRoomCapacity
--SET 
--    (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[MyTable_Archive] , DATA_CONSISTENCY_CHECK = ON ))
--GO