/*
Server A : Your Laptop
Server B : dbTest VM
*/
--------------------------------------------------------------------
--Server A ایجاد بانک اطلاعاتی بر روی  
USE master
GO
IF DB_ID('Test_ServerA')>0
BEGIN
	ALTER DATABASE Test_ServerA SET SINGLE_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE Test_ServerA
END
GO
CREATE DATABASE Test_ServerA
GO
USE Test_ServerA
GO
CREATE TABLE A_Tbl1 
(
	 ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	 Comments NVARCHAR(50) NULL 
) 
GO
CREATE TABLE A_Tbl2 
(
	 ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	 Comments NVARCHAR(50) NULL 
) 
GO
CREATE TABLE A_Tbl3 
(
	 ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	 Comments NVARCHAR(50) NULL 
) 
GO
CREATE TABLE B_Tbl1 
(
	 ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	 Comments NVARCHAR(50) NULL 
) 
GO
CREATE TABLE B_Tbl2 
(
	 ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	 Comments NVARCHAR(50) NULL 
) 
GO
CREATE TABLE B_Tbl3 
(
	 ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	 Comments NVARCHAR(50) NULL 
) 
GO
INSERT INTO dbo.A_Tbl1 VALUES ('Hello'), ('Hi');
INSERT INTO dbo.A_Tbl2 VALUES ('dbTest'), ('Night');
INSERT INTO dbo.A_Tbl3 VALUES ('SQL Server'), ('Oracle');
GO
SELECT * FROM A_Tbl1
SELECT * FROM A_Tbl2
SELECT * FROM A_Tbl3
GO
--------------------------------------------------------------------
--Server B ایجاد بانک اطلاعاتی بر روی  
USE master
GO
IF DB_ID('Test_ServerB')>0
BEGIN
	ALTER DATABASE Test_ServerB SET SINGLE_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE Test_ServerB
END
GO
CREATE DATABASE Test_ServerB
GO
USE Test_ServerB
GO
CREATE TABLE A_Tbl1 
(
	 ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	 Comments NVARCHAR(50) NULL 
) 
GO
CREATE TABLE A_Tbl2 
(
	 ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	 Comments NVARCHAR(50) NULL 
) 
GO
CREATE TABLE A_Tbl3 
(
	 ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	 Comments NVARCHAR(50) NULL 
) 
GO
CREATE TABLE B_Tbl1 
(
	 ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	 Comments NVARCHAR(50) NULL 
) 
GO
CREATE TABLE B_Tbl2 
(
	 ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	 Comments NVARCHAR(50) NULL 
) 
GO
CREATE TABLE B_Tbl3 
(
	 ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	 Comments NVARCHAR(50) NULL 
) 
GO
INSERT INTO dbo.B_Tbl1 VALUES ('Yes'), ('No');
INSERT INTO dbo.B_Tbl1 VALUES ('Food'), ('Drink');
INSERT INTO dbo.B_Tbl1 VALUES ('See ya'), ('Bye');
GO
SELECT * FROM B_Tbl1
SELECT * FROM B_Tbl2
SELECT * FROM B_Tbl3
GO
