EXEC sp_resetstatus 'db_name'
Go
ALTER DATABASE 'database_name' SET EMERGENCY
Go
DBCC CHECKDB (Database_Name)
Go
ALTER DATABASE [database_name] SINGLE_USER WITH ROLLBACK IMMEDIATE
Go
DBCC CHECKDB (N'database_name', REPAIR_ALLOW_DATA_LOSS) WITH ALL_ERRORMSGS, NO_INFOMSGS;
Go
ALTER DATABASE database_name SET MULTI_USER
Go
ALTER DATABASE database_name SET ONLINE
