USE [BPMS]
Go
ALTER DATABASE [BPMS] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
Go
DECLARE @DatabaseName NVARCHAR(50)
DECLARE @SPId int
DECLARE @SQL NVARCHAR(100)

SET @DatabaseName = N'[BPMS]'
--SET @DatabaseName = DB_NAME()
DECLARE my_cursor CURSOR FAST_FORWARD FOR
SELECT SPId FROM MASTER..SysProcesses
WHERE DBId = DB_ID(@DatabaseName) AND SPId <> @@SPId

OPEN my_cursor

FETCH NEXT FROM my_cursor INTO @SPId

WHILE @@FETCH_STATUS = 0
BEGIN
 SET @SQL = 'KILL ' + CAST(@SPId as NVARCHAR(10))
 print @SQL
 --EXEC sp_executeSQL @SQL
 
 FETCH NEXT FROM my_cursor INTO @SPId
END

CLOSE my_cursor
DEALLOCATE my_cursor
Go
ALTER DATABASE [BPMS]  
    COLLATE Persian_100_CI_AI ;  
GO  
ALTER DATABASE [BPMS] SET MULTI_USER
Go
