SELECT 
	TABLE_NAME,
	COLUMN_NAME,
	DATA_TYPE,
	CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE 
(
	DATA_TYPE IN ('TEXT','NTEXT','IMAGE') OR
	(DATA_TYPE IN ('VARCHAR','NVARCHAR','VARBINARY') AND CHARACTER_MAXIMUM_LENGTH=-1)
)
GO